- name: Try to stop the PostgresSQL Service
  block:
    - name: Stop postgres service
      service:
        name: postgres.service
        state: started
        enabled: true
  rescue:
    - debug:
        msg: 'Service not found'
  when: service is defined and service == True

- name: Check if docker-compose.yml file exists
  stat:
    path: '{{ project_dir }}/postgres/docker-compose.yml'
  register: result
  when: service is not defined or service == False

- name: Run Docker Compose down
  docker_compose:
    project_src: '{{ project_dir }}/postgres'
    state: absent
    remove_volumes: '{{ remove_volumes }}'
  when: (service is not defined or service == False) and result.stat.exists

- name: Remove the postgres.service file
  file:
    path: '/etc/systemd/system/postgres.service'
    state: absent
  when: service is defined and service == True

- name: Delete the service folder
  file:
    path: '{{ project_dir }}/postgres'
    state: absent