- name: Check if docker-compose.yml file exists
  stat:
    path: '{{ project_dir }}/postgres/docker-compose.yml'
  register: result

- name: Run Docker Compose down
  docker_compose:
    project_src: '{{ project_dir }}/postgres'
    state: absent
    remove_volumes: '{{ remove_volumes }}'
  when: result.stat.exists

- name: Delete folder is 'state' is absent
  file:
    path: '{{ project_dir }}/postgres'
    state: absent