---
- name: Check variables
  assert:
    that:
      - project_dir is defined
      - sql_scripts is iterable

- import_tasks: ./present.yml
  when: state == 'present'

- import_tasks: ./absent.yml
  when: state == 'absent'